### ISSUE TITLE
Potential infinite loop when hitting a specific method

### ISSUE THREAD

**Issue by jonathan-m-phillips** [njit-jerse/specimin#272]
Running ASHE on dryrun mode, we haven gotten hung up on the same method multiple times for hours. This makes me think there is an infinite loop when minimizing a specific method.

`--outputDirectory "/my/temp/dir" --root "/my/root/checker-framework/framework/src/main/java" --targetFile "org/checkerframework/framework/util/typeinference8/types/AbstractType.java" --targetMethod "org.checkerframework.framework.util.typeinference8.types.AbstractType#getFunctionTypeParameterTypes()"`

java.lang.RuntimeException: Unfound parent for this class: JavaExpression
Caused by: UnsolvedSymbolException{context='mapList', name='CollectionsPlume.mapList(JavaExpression::fromNode, invocationNode.getArguments())', cause='null'}

That is the most consistent error, but there were two other times it appeared we hit an infinite loop at different methods:
`--outputDirectory "/my/temp/dir" --root "/my/root/checker-framework/framework/src/main/java" --targetFile "org/checkerframework/framework/util/Contract.java" --targetMethod "org.checkerframework.framework.util.Contract#viewpointAdaptDependentTypeAnnotation(GenericAnnotatedTypeFactory<?,?,?,?>, StringToJavaExpression, Tree)"`

`--outputDirectory "/my/temp/dir" --root "/my/root/checker-framework/dataflow/src/main/java" --targetFile "org/plumelib/util/ArrayMap.java" --targetMethod "org.plumelib.util.ArrayMap#newArrayMapOrLinkedHashMap(int)"`

**Comment by jonathan-m-phillips** [comment]
Another targeted method I found with an infinite loop:
`--outputDirectory "/temp/dir" --root "/my/root/randoop/src/main/java" --targetFile "randoop/output/PrimitiveAndWrappedTypeVarNameCollector.java" --targetMethod "randoop.output.PrimitiveAndWrappedTypeVarNameCollector#visit(VariableDeclarationExpr, Set<String>)"`

If you would like me to create a new issue for this, please let me know.

**Comment by kelloggm** [comment]
> If you would like me to create a new issue for this, please let me know.

Please do. This issue should have been closed when I merged #275.
